apiVersion: v2
name: matilda-prometheus-stack
description: Matilda Cloud Prometheus Stack - A comprehensive monitoring solution with Prometheus, AlertManager, and Grafana
type: application
version: 0.1.0
appVersion: v3.3.1
keywords:
  - monitoring
  - prometheus
  - alertmanager
  - grafana
  - matilda
  - stack
maintainers:
  - name: Matilda Cloud Team
    email: githubadmin@matildacloud.com
home: https://github.com/matildacloud/helm-charts
sources:
  - https://github.com/matildacloud/helm-charts
dependencies:
- condition: alertmanager.enabled
  name: alertmanager
  repository: https://prometheus-community.github.io/helm-charts
  version: 1.18.*
- condition: kube-state-metrics.enabled
  name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: 5.33.*
- condition: prometheus-node-exporter.enabled
  name: prometheus-node-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 4.46.*
- condition: prometheus-pushgateway.enabled
  name: prometheus-pushgateway
  repository: https://prometheus-community.github.io/helm-charts
  version: 3.2.*
kubeVersion: '>=1.19.0-0'
