# Default values for matilda-prometheus-stack
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Matilda Cloud Configuration
matilda:
  # Enable Matilda Cloud integration
  enabled: true
  # Matilda Cloud cluster identifier
  clusterId: "optimize-global"
  # Matilda Cloud endpoint for remote write
  endpoint: "http://3.133.88.149:30003/api/v1/receive"

## The remote_write spec configuration for Prometheus.
## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#remotewritespec
remoteWrite: 
  - url: "http://3.133.88.149:30003/api/v1/receive"
    remote_timeout: 30s
    write_retries: 10
    external_labels:
      cluster: "optimize-global"
      environment: "production"
      team: "matilda"

## Prometheus Server Configuration
server:
  # Enable Prometheus server
  enabled: true
  # Prometheus server image
  image:
    repository: prom/prometheus
    tag: v3.3.1
    pullPolicy: IfNotPresent
  
  # Service configuration
  service:
    type: ClusterIP
    port: 80
    targetPort: 9090
  
  # Ingress configuration
  ingress:
    enabled: false
    annotations: {}
    hosts: []
    tls: []
  
  # Persistent volume configuration
  persistentVolume:
    enabled: true
    size: 50Gi
    storageClass: ""
  
  # Resource limits
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

## AlertManager Configuration
alertmanager:
  # Enable AlertManager
  enabled: true
  # AlertManager image
  image:
    repository: prom/alertmanager
    tag: v0.27.0
    pullPolicy: IfNotPresent
  
  # Service configuration
  service:
    type: ClusterIP
    port: 80
    targetPort: 9093
  
  # Persistent volume configuration
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: ""
  
  # Resource limits
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

## Kube State Metrics Configuration
kube-state-metrics:
  # Enable kube-state-metrics
  enabled: true
  # Resource limits
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

## Prometheus Node Exporter Configuration
prometheus-node-exporter:
  # Enable node exporter
  enabled: true
  # Resource limits
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

## Prometheus Pushgateway Configuration
prometheus-pushgateway:
  # Enable pushgateway
  enabled: true
  # Resource limits
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

## RBAC Configuration
rbac:
  # Create RBAC resources
  create: true

## Service Account Configuration
serviceAccounts:
  server:
    create: true
    name: "matilda-prometheus-server"
    annotations: {}
  alertmanager:
    create: true
    name: "matilda-alertmanager"
    annotations: {}
  kube-state-metrics:
    create: true
    name: "matilda-kube-state-metrics"
    annotations: {}
  prometheus-node-exporter:
    create: true
    name: "matilda-node-exporter"
    annotations: {}
  prometheus-pushgateway:
    create: true
    name: "matilda-pushgateway"
    annotations: {}

## Security Context
securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534

## Node Selector
nodeSelector: {}

## Tolerations
tolerations: []

## Affinity
affinity: {} 