{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "thanos.common.labels" . | nindent 4 }}
    app.kubernetes.io/component: namespace
{{- end }}
