apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  namespace: thanos
  labels:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: thanos-query
    app.kubernetes.io/name: thanos-query
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: thanos-query
    app.kubernetes.io/name: thanos-query
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      nodePort: {{ .Values.service.grpcNodePort }}
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      nodePort: {{ .Values.service.httpNodePort }}
