apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: thanos-query
    app.kubernetes.io/name: thanos-query
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  type: {{ .Values.query.service.type }}
  selector:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: thanos-query
    app.kubernetes.io/name: thanos-query
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      {{- if eq .Values.query.service.type "NodePort" }}
      nodePort: {{ .Values.query.service.grpcNodePort }}
      {{- end }}
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      {{- if eq .Values.query.service.type "NodePort" }}
      nodePort: {{ .Values.query.service.httpNodePort }}
      {{- end }}
