apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.receiveIngestor.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: {{ .Values.receiveIngestor.labels.component }}
    app.kubernetes.io/instance: {{ .Values.receiveIngestor.labels.instance }}
    app.kubernetes.io/name: {{ .Values.receiveIngestor.labels.name }}
    app.kubernetes.io/version: {{ .Values.receiveIngestor.image.tag }}
  annotations:
    {{- with .Values.receiveIngestor.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

