apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.query.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: {{ .Values.query.labels.component }}
    app.kubernetes.io/instance: {{ .Values.query.labels.instance }}
    app.kubernetes.io/name: {{ .Values.query.labels.name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations: {{ toYaml .Values.query.serviceAccount.annotations | nindent 4 }}

