{{- if .Values.persistence.receive.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-thanos-receive-pv3
spec:
  capacity:
    storage: {{ .Values.persistence.receive.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistence.receive.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.receive.reclaimPolicy }}
  hostPath:
    path: {{ .Values.persistence.receive.hostPath }}
  storageClassName: {{ .Values.persistence.receive.storageClassName }}
{{- end }}
