apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "thanos.store.fullname" . }}
  namespace: {{ .Values.store.namespace }}
  labels:
    {{- include "thanos.store.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.store.replicaCount }}
  serviceName: {{ .Values.store.service.name }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.store.labels.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ .Values.store.labels.component }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.store.labels.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: {{ .Values.store.labels.component }}
        app.kubernetes.io/version: {{ .Values.store.labels.version }}
    spec:
      serviceAccountName: {{ .Values.store.serviceAccount.name }}
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .Values.store.affinity.podAntiAffinity.weight }}
              podAffinityTerm:
                topologyKey: {{ index .Values.store.affinity.podAntiAffinity.topologyKeys 0 }}
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - {{ .Values.store.labels.name }}
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - {{ .Release.Name }}
                namespaces:
                  - {{ .Values.namespace }}
      terminationGracePeriodSeconds: {{ .Values.store.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.store.securityContext.pod | nindent 8 }}
      containers:
        - name: {{ .Values.store.labels.name }}
          image: "{{ .Values.store.image.repository }}:{{ .Values.store.image.tag }}"
          imagePullPolicy: {{ .Values.store.image.pullPolicy }}
          args:
            - store
            - --log.level=info
            - --log.format=logfmt
            - --data-dir=/var/thanos/store
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --objstore.config=$(OBJSTORE_CONFIG)
            - --ignore-deletion-marks-delay=24h
          env:
            - name: OBJSTORE_CONFIG
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.store.objstore.secretName }}
                  key: {{ .Values.store.objstore.secretKey }}
            - name: HOST_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - name: grpc
              containerPort: {{ .Values.store.ports.grpc }}
            - name: http
              containerPort: {{ .Values.store.ports.http }}
          volumeMounts:
            - name: {{ .Values.store.volume.name }}
              mountPath: /var/thanos/store
          livenessProbe:
            httpGet:
              path: {{ .Values.store.probes.liveness.path }}
              port: {{ .Values.store.probes.liveness.port }}
              scheme: {{ .Values.store.probes.liveness.scheme }}
            periodSeconds: {{ .Values.store.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.store.probes.liveness.failureThreshold }}
            timeoutSeconds: {{ .Values.store.probes.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.store.probes.readiness.path }}
              port: {{ .Values.store.probes.readiness.port }}
              scheme: {{ .Values.store.probes.readiness.scheme }}
            periodSeconds: {{ .Values.store.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.store.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.store.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.store.securityContext.container | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.store.volume.name }}
        labels:
          app.kubernetes.io/name: {{ .Values.store.labels.name }}
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/component: {{ .Values.store.labels.component }}
      spec:
        accessModes:
          {{- toYaml .Values.store.volume.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.store.volume.storage }}

