apiVersion: v1
kind: Service
metadata:
  name: thanos-receive-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/component: receive-ingestor
    app.kubernetes.io/instance: thanos-receive
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    controller.receive.thanos.io/hashring: hashring-v1
spec:
  type: {{ .Values.receiveService.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.receiveService.ports.grpc }}
      targetPort: {{ .Values.receiveService.ports.grpc }}
      {{- if eq .Values.receiveService.service.type "NodePort" }}
      nodePort: {{ .Values.receiveService.service.grpcNodePort }}
      {{- end }}
    - name: http
      port: {{ .Values.receiveService.ports.http }}
      targetPort: {{ .Values.receiveService.ports.http }}
      {{- if eq .Values.receiveService.service.type "NodePort" }}
      nodePort: {{ .Values.receiveService.service.httpNodePort }}
      {{- end }}
    - name: remote-write
      port: {{ .Values.receiveService.ports.remoteWrite }}
      targetPort: {{ .Values.receiveService.ports.remoteWrite }}
      {{- if eq .Values.receiveService.service.type "NodePort" }}
      nodePort: {{ .Values.receiveService.service.remoteWriteNodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/component: receive-ingestor
    app.kubernetes.io/instance: thanos-receive
    app.kubernetes.io/name: thanos-receive
    controller.receive.thanos.io/hashring: hashring-v1

