apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.store.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations: {{- toYaml .Values.store.serviceAccount.annotations | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ .Values.store.labels.component }}
    app.kubernetes.io/instance: {{ .Values.store.labels.instance }}
    app.kubernetes.io/name: {{ .Values.store.labels.name }}
    app.kubernetes.io/version: {{ .Values.store.image.tag }}

