apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.receiveStatefulSet.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: {{ .Values.receiveStatefulSet.labels.component }}
    app.kubernetes.io/instance: {{ .Values.receiveStatefulSet.labels.instance }}
    app.kubernetes.io/name: {{ .Values.receiveStatefulSet.labels.name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    controller.receive.thanos.io: {{ .Values.receiveStatefulSet.labels.controller }}
    controller.receive.thanos.io/hashring: {{ .Values.receiveStatefulSet.labels.hashring }}
spec:
  minReadySeconds: {{ .Values.receiveStatefulSet.minReadySeconds }}
  replicas: {{ .Values.receiveStatefulSet.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.receiveStatefulSet.labels.component }}
      app.kubernetes.io/instance: {{ .Values.receiveStatefulSet.labels.instance }}
      app.kubernetes.io/name: {{ .Values.receiveStatefulSet.labels.name }}
      controller.receive.thanos.io/hashring: {{ .Values.receiveStatefulSet.labels.hashring }}
  serviceName: {{ .Values.receiveStatefulSet.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ .Values.receiveStatefulSet.labels.component }}
        app.kubernetes.io/instance: {{ .Values.receiveStatefulSet.labels.instance }}
        app.kubernetes.io/name: {{ .Values.receiveStatefulSet.labels.name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        controller.receive.thanos.io/hashring: {{ .Values.receiveStatefulSet.labels.hashring }}
    spec:
      serviceAccountName: "{{ .Values.receiveStatefulSet.serviceAccountName }}"
      terminationGracePeriodSeconds: {{ .Values.receiveStatefulSet.terminationGracePeriodSeconds }}
      affinity:
        {{- toYaml .Values.receiveStatefulSet.affinity | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.receiveStatefulSet.nodeSelector | nindent 8 }}
      securityContext:
        {{- toYaml .Values.receiveStatefulSet.podSecurityContext | nindent 8 }}
      volumes:
        - name: hashring-config
          configMap:
            name: hashring-config
      containers:
        - name: thanos-receive
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - receive
            - --log.level=info
            - --log.format=logfmt
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --remote-write.address=0.0.0.0:19291
            - --receive.replication-factor=1
            - --tsdb.path=/var/thanos/receive
            - --tsdb.retention=15d
            - --label=replica="$(NAME)"
            - --label=receive="true"
            - --label=receive_cluster="eks-dev"
            - --receive.local-endpoint=$(NAME).thanos-receive-ingestor-default.$(NAMESPACE).svc.cluster.local:10901
            - --receive.hashrings-file=/var/lib/thanos-receive/hashrings.json
            - --objstore.config=$(OBJSTORE_CONFIG)
          env:
            - name: OBJSTORE_CONFIG
              valueFrom:
                secretKeyRef:
                  key: thanos.yaml
                  name: thanos-objectstorage
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - name: grpc
              containerPort: {{ .Values.service.ports.grpc }}
            - name: http
              containerPort: {{ .Values.service.ports.http }}
            - name: remote-write
              containerPort: {{ .Values.service.ports.remoteWrite }}
          livenessProbe:
            {{- toYaml .Values.receiveStatefulSet.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.receiveStatefulSet.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - name: data
              mountPath: /var/thanos/receive
            - name: hashring-config
              mountPath: /var/lib/thanos-receive
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/component: {{ .Values.receiveStatefulSet.labels.component }}
          app.kubernetes.io/instance: {{ .Values.receiveStatefulSet.labels.instance }}
          app.kubernetes.io/name: {{ .Values.receiveStatefulSet.labels.name }}
          controller.receive.thanos.io/hashring: {{ .Values.receiveStatefulSet.labels.hashring }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.receiveStatefulSet.storage }}

