{{- if .Values.persistence.store.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-thanos-store-pv3
spec:
  capacity:
    storage: {{ .Values.persistence.store.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistence.store.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.store.reclaimPolicy }}
  hostPath:
    path: {{ .Values.persistence.store.hostPath }}
  storageClassName: {{ .Values.persistence.store.storageClassName }}
{{- end }}
