apiVersion: v1
kind: Service
metadata:
  name: thanos-store
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: object-store-gateway
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/name: thanos-store
    app.kubernetes.io/version: {{ .Values.image.tag }}
spec:
  type: {{ .Values.store.service.type }}
  {{- if eq .Values.store.service.type "NodePort" }}
  clusterIP: None
  {{- end }}
  ports:
    - name: grpc
      port: {{ .Values.store.ports.grpc }}
      targetPort: {{ .Values.store.ports.grpc }}
      {{- if eq .Values.store.service.type "NodePort" }}
      nodePort: {{ .Values.store.service.grpcNodePort }}
      {{- end }}
    - name: http
      port: {{ .Values.store.ports.http }}
      targetPort: {{ .Values.store.ports.http }}
      {{- if eq .Values.store.service.type "NodePort" }}
      nodePort: {{ .Values.store.service.httpNodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/component: object-store-gateway
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/name: thanos-store

