{{- include "thanos.validations.namespace" . -}}
{{- include "thanos.validations.image" . -}}
{{- include "thanos.validations.resources" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: thanos-query
    app.kubernetes.io/name: thanos-query
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.query.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: query-layer
      app.kubernetes.io/instance: thanos-query
      app.kubernetes.io/name: thanos-query
  template:
    metadata:
      labels:
        app.kubernetes.io/component: query-layer
        app.kubernetes.io/instance: thanos-query
        app.kubernetes.io/name: thanos-query
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
    spec:
      {{- with .Values.query.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: thanos-query
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - query
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:9090
            - --log.level=info
            - --log.format=logfmt
            - --query.replica-label=prometheus_replica
            - --query.replica-label=rule_replica
            - --endpoint=dnssrv+_grpc._tcp.thanos-store.{{ .Values.namespace.name }}.svc.cluster.local:10901
            - --endpoint=dnssrv+_grpc._tcp.thanos-receive-ingestor-default.{{ .Values.namespace.name }}.svc.cluster.local:10901
            {{- if .Values.ruler.enabled }}
            - --endpoint=dnssrv+_grpc._tcp.thanos-ruler.{{ .Values.namespace.name }}.svc.cluster.local:10901
            {{- end }}
            - --store=dnssrv+_grpc._tcp.thanos-store.{{ .Values.namespace.name }}.svc.cluster.local:10901
            - --store=dnssrv+_grpc._tcp.prometheus-kube-prometheus-thanos-discovery.prometheus.svc.cluster.local:10901
            - --query.auto-downsampling
          env:
            - name: HOST_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - containerPort: {{ .Values.service.grpcPort }}
              name: grpc
            - containerPort: {{ .Values.service.httpPort }}
              name: http
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: {{ .Values.service.httpPort }}
              scheme: HTTP
            periodSeconds: 30
            failureThreshold: 8
          readinessProbe:
            httpGet:
              path: /-/ready
              port: {{ .Values.service.httpPort }}
              scheme: HTTP
            periodSeconds: 5
            failureThreshold: 20
          resources:
            {{- toYaml .Values.query.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePolicy: File
      {{- with .Values.query.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 65534
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ .Values.query.serviceAccount.name }}
      terminationGracePeriodSeconds: 120

