apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.store.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/component: object-store-gateway
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/name: thanos-store
    app.kubernetes.io/version: {{ .Values.image.tag }}

