apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.receiveIngestor.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/component: receive-ingestor
    app.kubernetes.io/instance: thanos-receive
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/version: {{ .Values.image.tag }}

