{{- if .Values.store.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.store.serviceMonitor.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/component: object-store-gateway
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/name: thanos-store
    app.kubernetes.io/version: {{ .Values.image.tag }}
spec:
  endpoints:
    - port: {{ .Values.store.serviceMonitor.port }}
      relabelings:
        - action: replace
          separator: /
          sourceLabels:
            - namespace
            - pod
          targetLabel: instance
  selector:
    matchLabels:
      app.kubernetes.io/component: object-store-gateway
      app.kubernetes.io/instance: thanos-store
      app.kubernetes.io/name: thanos-store
{{- end }}

