apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-receive
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/component: receive-ingestor
    app.kubernetes.io/instance: thanos-receive
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    controller.receive.thanos.io: receive-controller
    controller.receive.thanos.io/hashring: hashring-v1
spec:
  minReadySeconds: {{ .Values.receiveStatefulSet.minReadySeconds }}
  replicas: {{ .Values.receiveStatefulSet.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: receive-ingestor
      app.kubernetes.io/instance: thanos-receive
      app.kubernetes.io/name: thanos-receive
      controller.receive.thanos.io/hashring: hashring-v1
  serviceName: thanos-receive
  template:
    metadata:
      labels:
        app.kubernetes.io/component: receive-ingestor
        app.kubernetes.io/instance: thanos-receive
        app.kubernetes.io/name: thanos-receive
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        controller.receive.thanos.io/hashring: hashring-v1
    spec:
      serviceAccountName: "{{ .Values.receiveStatefulSet.serviceAccountName }}"
      terminationGracePeriodSeconds: 120
      {{- with .Values.receiveStatefulSet.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receiveStatefulSet.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 65534
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
        - name: hashring-config
          configMap:
            name: hashring-config
      containers:
        - name: thanos-receive
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - receive
            - --log.level=info
            - --log.format=logfmt
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --remote-write.address=0.0.0.0:19291
            - --receive.replication-factor=1
            - --tsdb.path=/var/thanos/receive
            - --tsdb.retention=15d
            - --label=replica="$(NAME)"
            - --label=receive="true"
            - --label=receive_cluster="eks-dev"
            - --receive.local-endpoint=$(NAME).thanos-receive-ingestor-default.$(NAMESPACE).svc.cluster.local:10901
            - --receive.hashrings-file=/var/lib/thanos-receive/hashrings.json
            - --objstore.config=$(OBJSTORE_CONFIG)
          env:
            - name: OBJSTORE_CONFIG
              valueFrom:
                secretKeyRef:
                  key: thanos.yaml
                  name: thanos-objectstorage
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
            - name: http
              containerPort: {{ .Values.service.httpPort }}
            - name: remote-write
              containerPort: {{ .Values.service.remoteWritePort }}
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 10902
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 8
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 10902
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 20
          resources:
            {{- toYaml .Values.receiveIngestor.resources | nindent 12 }}
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - name: data
              mountPath: /var/thanos/receive
            - name: hashring-config
              mountPath: /var/lib/thanos-receive
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: thanos-receive
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/component: receive-ingestor
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.receiveStatefulSet.storage }}
        {{- if .Values.receiveStatefulSet.storageClassName }}
        storageClassName: {{ .Values.receiveStatefulSet.storageClassName }}
        {{- end }}

