{{- if .Values.query.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.query.serviceMonitor.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: thanos-query
    app.kubernetes.io/name: thanos-query
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  endpoints:
    - port: {{ .Values.query.serviceMonitor.port }}
      relabelings:
        - action: replace
          separator: /
          sourceLabels:
            - namespace
            - pod
          targetLabel: instance
  selector:
    matchLabels:
      app.kubernetes.io/component: query-layer
      app.kubernetes.io/instance: thanos-query
      app.kubernetes.io/name: thanos-query
{{- end }}

