# Default values for matilda-prometheus
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## The remote_write spec configuration for Prometheus.
## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#remotewritespec
remoteWrite: 
  - url: http://3.133.88.149:30003/api/v1/receive
    remote_timeout: 30s
    write_retries: 10
    external_labels:
      cluster: "optimize-global" 