{{- if and .Values.rbac.create .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name }}
  labels:
    app: {{ include "matilda-k8s-svc.name" . }}
    chart: {{ include "matilda-k8s-svc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
{{- toYaml .Values.clusterRole.rules | nindent 2 }}
{{- end }} 