{{- if .Values.kubeconfig.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kubeconfig.name }}-secret
  namespace: {{ .Values.serviceAccount.namespace }}
  labels:
    app: {{ include "matilda-k8s-svc.name" . }}
    chart: {{ include "matilda-k8s-svc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  # This will be populated by a post-install hook
  kubeconfig: ""
{{- end }} 