apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matilda-k8s-agent.configMapName" . }}
  labels:
    {{- include "matilda-k8s-agent.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  # RabbitMQ Configuration (non-sensitive)
  rabbitmq.host: {{ .Values.rabbitMQ.host | quote }}
  rabbitmq.port: {{ .Values.rabbitMQ.port | quote }}
  rabbitmq.vhost: {{ .Values.rabbitMQ.vhost | quote }}
  rabbitmq.connectionTimeout: {{ .Values.rabbitMQ.connectionTimeout | quote }}
  rabbitmq.heartbeat: {{ .Values.rabbitMQ.heartbeat | quote }}
  
  # Logging Configuration
  logging.level: {{ .Values.logging.level | quote }}
  logging.format: {{ .Values.logging.format | quote }}
  
  # Application Configuration
  app.name: {{ include "matilda-k8s-agent.name" . | quote }}
  app.version: {{ .Chart.AppVersion | quote }} 