apiVersion: v1
kind: Service
metadata:
  name: metrics-exporter
  namespace: matilda-k8s-agent
spec:
  clusterIP: None
  selector:
    app: metrics-exporter
  ports:
    - port: 9184
      targetPort: 9184
