{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "matilda-k8s-agent.fullname" . }}-clusterrole
  labels:
    {{- include "matilda-k8s-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: clusterrole
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "matilda-k8s-agent.fullname" . }}-clusterrolebinding
  labels:
    {{- include "matilda-k8s-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: clusterrolebinding
roleRef:
  kind: ClusterRole
  name: {{ include "matilda-k8s-agent.fullname" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "matilda-k8s-agent.serviceAccountName" . }}
    namespace: {{ .Values.namespace.name | default .Release.Namespace }}
{{- end }}
