{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matilda-k8s-agent.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matilda-k8s-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
data:
  api-key: {{ .Values.api_key | b64enc | quote }}
  cluster-asset-id: {{ .Values.id | b64enc | quote }}
{{- end }}
