apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matilda-k8s-agent.secretName" . }}
  labels:
    {{- include "matilda-k8s-agent.labels" . | nindent 4 }}
type: Opaque
data:
  # Asset configuration (base64 encoded)
  assetid: {{ .Values.assetid | b64enc | quote }}
  integrationid: {{ .Values.integrationid | b64enc | quote }}
