apiVersion: v1
kind: Service
metadata:
  name: {{ include "matilda-k8s-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matilda-k8s-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "matilda-k8s-agent.selectorLabels" . | nindent 4 }} 
