apiVersion: v1
kind: Service
metadata:
  name: {{ include "matilda-k8s-agent.fullname" . }}
  labels:
    {{- include "matilda-k8s-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "matilda-k8s-agent.selectorLabels" . | nindent 4 }} 
